import { defineStore } from "pinia";

export let useMessageUserStore = defineStore({
    id:"Message store",
    state:()=>({
        name:"Salam",
        isSelected: false,
        chat:[
            {
                name:"Hesen",
                id:1,
                isSelected:false,
                profil:"../../src/static/contact1.png",
                messages:[
                    {
                        isYour:false,
                        content:"Salam",
                        time:"20:00"
                    },
                    {
                        isYour:true,
                        content:"Sagol"
                    },
                    {
                        isYour:true,
                        content:"Test"
                    },
                    {
                        isYour:false,
                        content:"Test2"
                    },
                    {
                        isYour:false,
                        content:"Salam"
                    },
                    {
                        isYour:true,
                        content:"Sagol"
                    },
                    {
                        isYour:true,
                        content:"Test"
                    },
                    {
                        isYour:false,
                        content:"Test2"
                    },
                    {
                        isYour:false,
                        content:"Salam"
                    },
                    {
                        isYour:true,
                        content:"Sagol"
                    },
                    {
                        isYour:true,
                        content:"Test"
                    },
                    {
                        isYour:false,
                        content:"Test2"
                    },
                ]
            },
            {
                name:"Eli",
                id:2,
                isSelected: false,
                profil:"../../src/static/contact2.png",
                messages:[
                    {
                        isYour:false,
                        content:"FUIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIEB",
                        time:"20:01"
                    },
                    {
                        isYour:true,
                        content:"Sagol"
                    },
                ]
            },
            {
                name:"Huseyn",
                id:3,
                isSelected: false,
                profil:"../../src/static/contact3.png",
                messages:[
                    {
                        isYour:false,
                        content:"Salam"
                    },
                    {
                        isYour:true,
                        content:"Sagol"
                    }
                ]
            },
                 ]
    })
})