import { defineStore } from "pinia";

export let useMessageUserStore = defineStore({
    id:"Message store",
    state:()=>({
        name:"Salam",
        chat:[
            {
                name:"Hesen",
                id:1,
                profil:"../../src/static/contact1.png",
                messages:[
                    {
                        isYour:false,
                        content:"Salam"
                    },
                    {
                        isYour:true,
                        content:"Sagol"
                    }
                ]
            },
            {
                name:"Eli",
                id:2,
                profil:"../../src/static/contact2.png",
                messages:[
                    {
                        isYour:false,
                        content:"Salam"
                    },
                    {
                        isYour:true,
                        content:"Sagol"
                    }
                ]
            },
            {
                name:"Huseyn",
                id:3,
                profil:"../../src/static/contact3.png",
                messages:[
                    {
                        isYour:false,
                        content:"Salam"
                    },
                    {
                        isYour:true,
                        content:"Sagol"
                    }
                ]
            },
                 ]
    })
})